### ISSUE TITLE
[Solver Tutorial] Include instructions on how to lower economic viability constraint

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-docs#49]
A common use case for running your own solver is to match profitable trades that are not economically viable in themselves (I had someone on discord reach out to me for that).

It would be nice if the tutorial could include instruction on how to lower the min_avg_fee_constraint to make sure even smaller but lucrative arbitrage opportunities can be used.

**Comment by bh2smith** [comment]
I am in the process of writing up a nice section "Advanced Configuration" with a component called "Economic Viability Constraints" that walks the user through a few different configuration scenarios. However, along the way I have realized that our current defaults are extremely dangerous to anyone who might think they can just supply a PK to an accounts with some ETH and just start mining OWL rewards. They may find themselves extremely disappointed spending 45$ worth of ETH just to make 0.13 OWL 😄...

Anyway, I have opened an issue https://github.com/gnosis/dex-services/issues/1512 and started looking into a reasonable solution for our default configuration that doesn't clash too much with CI. There is an open PR addressing the issue linked above here: https://github.com/gnosis/dex-services/pull/1513
